title: CoderDojo Arnhem
description: Bij CoderDojo Arnhem kunnen kinderen tussen de 7 en 17 jaar op een laagdrempelige manier kennis maken met technologie.
lang: nl_NL
logo: /static/cd-theme/img/coderdojo/coderdojo-arnhem.svg

social:
  name: CoderDojo Arnhem
  links:
    - https://www.facebook.com/CoderDojoArnhem/
    - https://twitter.com/CoderDojo026

google_site_verification: FVCdXbxuX231crX0C35SYJA3jygv1DCcDdnFzPjDSy8

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

defaults:
  -
    scope:
      path: "static/**/*.pdf"
    values:
      sitemap: false

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: [2]

paginate: 10
paginate_path: "/blog/pagina/:num/"
